### ISSUE TITLE
FreightText missing from ai2svelte.js

### ISSUE THREAD

**Issue by MinamiFunakoshiTR** [reuters-graphics/ai2svelte#8]
Our current ai2svelte script doesn't convert the FreightText font family.

## Suggested fixes

- Add `freight: "FreightTextPro,Georgia,serif",` to the [fontFamilies object](https://github.com/reuters-graphics/ai2svelte/blob/master/ai2svelte.js#L3372-L3380)
- Add `freight` to the [regex expression in this line](https://github.com/reuters-graphics/ai2svelte/blob/master/ai2svelte.js#L3421) so it looks like this: 
    `var family = aifont.match(/(source|knowledge|menlo|arial|georgia|freight|)/gi);
`

I've tested these two changes in my local ai2svelte.js file and checked that they work.

@hobbes7878  @man-shar  @fcage please let me know if this looks good and I can push the change.

**Comment by man-shar** [comment]
Looks good!

**Comment by MinamiFunakoshiTR** [comment]
Fixed in this commit https://github.com/reuters-graphics/ai2svelte/commit/88260dafc4566b4644618926e6dbfdb78e474f05
